FIELDEFFECTS = {
	PBFields::NONE => { #can also be used as a prototype!
		:FIELDNAME => nil,
		:INTROMESSAGE => nil,
		:FIELDGRAPHICS => "Indoor",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:MOVEDAMAGEBOOST => {},
		:MOVEMESSAGES => {},
		:MOVETYPEMOD => {},
		:MOVETYPECHANGE => {},
		:MOVEACCURACYBOOST => {},
		:TYPEDAMAGEBOOST => {},
		:TYPEMESSAGES => {},
		:TYPECONDITION => {},
		:TYPETYPEMOD => {}, #type modifier based on original type
		:TYPETYPECHANGE => {},
		:FIELDCHANGE => {},
		:DONTCHANGEBACKUP => [],
		:CHANGEMESSAGE => {},
		:CHANGECONDITION => {},
		:CHANGEEFFECTS => {},
		:SEED => nil,
		:SEEDEFFECT => nil,
		:SEEDEFFECTVAL => nil,
		:SEEDEFFECTSTR => nil,
		:SEEDANIM => nil,
		:SEEDSTATS => {}
		},
	# 1 Electric Terrain
	PBFields::ELECTRICT => {
		:FIELDNAME => "Electric Terrain",
		:INTROMESSAGE => "The field is hyper-charged!",
		:FIELDGRAPHICS => "Electric",
		:SECRETPOWERANIM => :SHOCKWAVE,
		:NATUREMOVES => :THUNDERBOLT,
		:MIMICRY => :ELECTRIC,
		:MOVEDAMAGEBOOST => {
		1.5 => [:EXPLOSION, :SELFDESTRUCT, :HURRICANE, :SURF,
						:SMACKDOWN, :MUDDYWATER, :THOUSANDARROWS],
		2.0 => [:MAGNETBOMB]},
		:MOVEMESSAGES => {
		"The explosion became hyper-charged!" => [:EXPLOSION, :SELFDESTRUCT],
		"The attack became hyper-charged!" => [:HURRICANE, :SURF, 
			:SMACKDOWN, :MUDDYWATER, :THOUSANDARROWS],
		"The attack powered up!" => [:MAGNETBOMB]},
		:MOVETYPEMOD => {
		:ELECTRIC => [:EXPLOSION, :SELFDESTRUCT, :SMACKDOWN, 
			:SURF, :MUDDYWATER, :HURRICANE, :THOUSANDARROWS, :HYDROVORTEX]},
		:MOVEACCURACYBOOST => {},
		:TYPEDAMAGEBOOST => {1.5 => [:ELECTRIC]},
		:TYPEMESSAGES => {"The Electric Terrain strengthened the attack!" => [:ELECTRIC]},
		:TYPECONDITION => {:ELECTRIC => "!attacker.isAirborne?" },
		:FIELDCHANGE => {0 => [:MUDSPORT, :TECTONICRAGE]},
		:CHANGEMESSAGE => {"The hyper-charged terrain shorted out!" => [:MUDSPORT, :TECTONICRAGE]},
		:STATUSMOVEBOOST => [:CHARGE, :EERIEIMPULSE,:MAGNETRISE],
		:CHANGEEFFECTS => {},
		:SEED => :ELEMENTALSEED,
		:SEEDEFFECT => :Charge,
		:SEEDEFFECTVAL => 2,
		:SEEDEFFECTSTR => "{1} began charging power!",
		:SEEDANIM => :CHARGE,
		:SEEDSTATS => {PBStats::SPEED => 1}
		},
	# 2 Grassy Terrain
	PBFields::GRASSYT => {
		:FIELDNAME => "Grassy Terrain",
		:INTROMESSAGE => "The field is in full bloom.",
		:FIELDGRAPHICS =>  "Grassy",
		:SECRETPOWERANIM => :SEEDBOMB,
		:NATUREMOVES => :ENERGYBALL,
		:MIMICRY => :GRASS,
		:MOVEDAMAGEBOOST => {
		1.5 => [:FAIRYWIND, :SILVERWIND],
		0.5 => [:MUDDYWATER, :SURF, :EARTHQUAKE,
						:MAGNITUDE, :BULLDOZE]
		},
		:MOVEACCURACYBOOST => {80 => [:GRASSWHISTLE]},
		:MOVEMESSAGES => {
		"The wind picked up strength from the field!" => [:FAIRYWIND, :SILVERWIND],
		"The grass softened the attack..." => [:MUDDYWATER, :SURF, 
			:EARTHQUAKE, :MAGNITUDE, :BULLDOZE]},
		:TYPEDAMAGEBOOST => {1.5 => [:GRASS,:FIRE]},
		:TYPEMESSAGES => {
		"The Grassy Terrain strengthened the attack!" => [:GRASS],
		"The grass below caught flame!" => [:FIRE]},
		:TYPECONDITION => {
			:GRASS => "!attacker.isAirborne?",
			:FIRE =>  "!opponent.isAirborne?"
		},
		:FIELDCHANGE => {
		PBFields::BURNINGF => PBFields::IGNITEMOVES,
		PBFields::CORROSIVEF => [:SLUDGEWAVE, :ACIDDOWNPOUR]},
		:DONTCHANGEBACKUP => PBFields::IGNITEMOVES + [:SLUDGEWAVE, :ACIDDOWNPOUR],
		:CHANGEMESSAGE => {
		"The grassy terrain caught fire!" => PBFields::IGNITEMOVES,
		"The grassy terrain was corroded!" => [:SLUDGEWAVE, :ACIDDOWNPOUR]},
		:CHANGECONDITION => {PBFields::BURNINGF => "ignitecheck"},
		:STATUSMOVEBOOST => [:COIL,:GROWTH,:FLORALHEALING,:GRASSWHISTLE],
		:CHANGEEFFECTS => {},
		:SEED => :ELEMENTALSEED,
		:SEEDEFFECT => :Ingrain,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} planted its roots!",
		:SEEDANIM => :INGRAIN,
		:SEEDSTATS => {PBStats::DEFENSE => 1}
		},
	# 3 Misty Terrain
	PBFields::MISTYT => {
		:FIELDNAME => "Misty Terrain",
		:INTROMESSAGE => "Mist settles on the field.",
		:FIELDGRAPHICS =>  "Misty",
		:SECRETPOWERANIM => :MISTBALL,
		:NATUREMOVES => :MISTBALL,
		:MIMICRY => :FAIRY,
		:MOVEDAMAGEBOOST => {
		1.5 => [:FAIRYWIND, :MYSTICALFIRE, :MOONBLAST, 
						:MAGICALLEAF, :DOOMDUMMY, :ICYWIND,
						:MISTBALL, :AURASPHERE, :STEAMERUPTION, 
						:DAZZLINGGLEAM, :SILVERWIND, :MOONGEISTBEAM],
		0.5 => [:DARKPULSE, :SHADOWBALL, :NIGHTDAZE]},
		:MOVEMESSAGES => {
		"The mist's energy strengthened the attack!" => [:FAIRYWIND, :MYSTICALFIRE, 
			:MOONBLAST, :MAGICALLEAF, :DOOMDUMMY, :ICYWIND, 
			:MISTBALL, :AURASPHERE, :STEAMERUPTION, :DAZZLINGGLEAM, 
			:SILVERWIND, :MOONGEISTBEAM],
		"The mist softened the attack..." => [:DARKPULSE, :SHADOWBALL, :NIGHTDAZE]},
		:TYPEDAMAGEBOOST => {0.5 => [:DRAGON]},
		:TYPEMESSAGES => {"The Misty Terrain weakened the attack!" => [:DRAGON]},
		:FIELDCHANGE => {0 => PBFields::BLOWMOVES},
		:CHANGEMESSAGE => {"The mist was blown away!" => PBFields::BLOWMOVES},
		:STATUSMOVEBOOST => [:COSMICPOWER, :AROMATICMIST, :SWEETSCENT],
		:CHANGEEFFECTS => {},
		:SEED => :ELEMENTALSEED,
		:SEEDEFFECT => :Wish,
		:SEEDEFFECTVAL => 2,
		:SEEDEFFECTSTR => "A wish was made for {1}!",
		:SEEDANIM => :WISH,
		:SEEDSTATS => {PBStats::SPDEF => 1}
		},
	# 4 Dark Crystal Cavern
	PBFields::DARKCRYSTALC => {
		:FIELDNAME => "Dark Crystal Cavern",
		:INTROMESSAGE => "Darkness is gathering...",
		:FIELDGRAPHICS => "DarkCrystalCavern",
		:SECRETPOWERANIM => :DARKPULSE,
		:NATUREMOVES => :DARKPULSE,
		:MIMICRY => :DARK,
		:MOVEDAMAGEBOOST => {
		1.5 => [:DARKPULSE, :NIGHTDAZE, :NIGHTSLASH,
						:SHADOWBALL, :SHADOWPUNCH, :SHADOWCLAW, 
						:SHADOWSNEAK, :SHADOWFORCE, :SHADOWBONE, 
						:AURORABEAM, :SIGNALBEAM, :FLASHCANNON, 
						:LUSTERPURGE, :DAZZLINGGLEAM, :MIRRORSHOT, 
						:TECHNOBLAST, :DOOMDUMMY, :POWERGEM, 
						:MOONGEISTBEAM, :PHOTONGEYSER, :DIAMONDSTORM,
						:MENACINGMOONRAZEMAELSTROM],
		2.0 => [:PRISMATICLASER, :BLACKHOLEECLIPSE],
		0.5 => [:LIGHTTHATBURNSTHESKY]},
		:MOVEACCURACYBOOST => {100 => [:DARKVOID]},
		:MOVEMESSAGES => {
		"The darkness began to gather...!" => [:DARKPULSE, :NIGHTDAZE, :NIGHTSLASH],
		"The darkness strengthened the attack!"	=> [:SHADOWBALL, :SHADOWPUNCH, 
			:SHADOWCLAW, :SHADOWSNEAK, :SHADOWFORCE, :SHADOWBONE,
			:MENACINGMOONRAZEMAELSTROM], 
		"The crystals' light strengthened the attack!" =>	[:AURORABEAM, 
			:SIGNALBEAM, :FLASHCANNON, :LUSTERPURGE, 
			:DAZZLINGGLEAM, :MIRRORSHOT, :TECHNOBLAST, 
			:DOOMDUMMY, :POWERGEM, :MOONGEISTBEAM, 
			:PHOTONGEYSER, :DIAMONDSTORM],
		"The crystal split the attack!" => [:PRISMATICLASER], 
		"The consuming darkness fed the attack!" => [:BLACKHOLEECLIPSE],
		"{1} couldn't consume much light..." => [:LIGHTTHATBURNSTHESKY]},
		:FIELDCHANGE => {
			PBFields::CAVE => PBFields::QUAKEMOVES,
			PBFields::CRYSTALC => [:SUNNYDAY]},
		:DONTCHANGEBACKUP => [:SUNNYDAY],
		:CHANGEMESSAGE => {
			"The dark crystals were shattered!" => PBFields::QUAKEMOVES,
			"The sun lit up the crystal cavern!" => [:SUNNYDAY]},
		:CHANGECONDITION => {PBFields::CRYSTALC => "suncheck"},
		:STATUSMOVEBOOST => [:FLASH, :DARKVOID, :MOONLIGHT],
		:CHANGEEFFECTS => {},
		:SEED => :MAGICALSEED,
		:SEEDEFFECT => :MagicCoat,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} shrouded itself with Magic Coat!",
		:SEEDANIM => :MAGICCOAT,
		:SEEDSTATS => {PBStats::SPDEF => 1}
		},
	# 5 Chess Board
	PBFields::CHESSB => {
		:FIELDNAME => "Chess Board",
		:INTROMESSAGE => "Opening variation set.",
		:FIELDGRAPHICS =>  "Chess",
		:SECRETPOWERANIM => :FEINT,
		:NATUREMOVES => :ANCIENTPOWER,
		:MIMICRY => :PSYCHIC,
		:MOVEDAMAGEBOOST => {1.5 => [:FEINT, :FEINTATTACK, :FAKEOUT, :SUCKERPUNCH, 
			:FIRSTIMPRESSION, :SHADOWSNEAK, :SMARTSTRIKE] + PBFields::CHESSMOVES},
		:MOVEMESSAGES => {"En passant!" => [:FEINT, :FEINTATTACK, :FAKEOUT,
			:SUCKERPUNCH, :FIRSTIMPRESSION, :SHADOWSNEAK, :SMARTSTRIKE]},
		:MOVETYPEMOD => {:ROCK => PBFields::CHESSMOVES},
		:FIELDCHANGE => {0 => [:STOMPINGTANTRUM, :TECTONICRAGE]},
		:CHANGEMESSAGE => {"The board was destroyed!" => [:STOMPINGTANTRUM, :TECTONICRAGE]},
		:STATUSMOVEBOOST => [:CALMMIND, :NASTYPLOT, :TRICKROOM],
		:CHANGEEFFECTS => {},
		:SEED => :SYNTHETICSEED,
		:SEEDEFFECT => :MagicCoat,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} shrouded itself with Magic Coat!",
		:SEEDANIM => :MAGICCOAT,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 6 Big Top Arena
	PBFields::BIGTOPA => {
		:FIELDNAME => "Big Top Arena",
		:INTROMESSAGE => "Now presenting...!",
		:FIELDGRAPHICS =>  "BigTop",
		:SECRETPOWERANIM => :DYNAMICPUNCH,
		:NATUREMOVES => :ACROBATICS,
		:MIMICRY => :NORMAL,
		:MOVEDAMAGEBOOST => {
		1.5 => [:VINEWHIP, :POWERWHIP, :FIRELASH, 
						:FIERYDANCE, :PETALDANCE, :REVELATIONDANCE, 
						:FLY, :ACROBATICS, :FIRSTIMPRESSION],
		2.0 => [:PAYDAY]},
		:MOVEACCURACYBOOST => {100 => [:SING]},
		:MOVEMESSAGES => {
		"Back, foul beast!" => [:VINEWHIP, :POWERWHIP, :FIRELASH], 
		"What grace!" => [:FIERYDANCE, :PETALDANCE, :REVELATIONDANCE], 
		"An extravagant aerial finish!" => [:FLY, :ACROBATICS], 
		"And what an entrance it is!" => [:FIRSTIMPRESSION],
		"And a little extra for you, darling!" => [:PAYDAY]},
		:STATUSMOVEBOOST => [:ENCORE, :DRAGONDANCE, :QUIVERDANCE, :SWORDSDANCE, :FEATHERDANCE,
			:SING, :RAINDANCE, :BELLYDRUM, :SPOTLIGHT],
		:CHANGEEFFECTS => {},
		:SEED => :SYNTHETICSEED,
		:SEEDEFFECT => :HelpingHand,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} accepts the crowd's help!",
		:SEEDANIM => :HELPINGHAND,
		:SEEDSTATS => {PBStats::ATTACK => 1}
		},
	# 7 Burning Field
	PBFields::BURNINGF => {
		:FIELDNAME => "Burning Field",
		:INTROMESSAGE => "The field is ablaze!",
		:FIELDGRAPHICS =>  "Burning",
		:SECRETPOWERANIM => :FLAMETHROWER,
		:NATUREMOVES => :FLAMETHROWER,
		:MIMICRY => :FIRE,
		:MOVEDAMAGEBOOST => {
		1.5 => [:SMOG, :CLEARSMOG],
		2.0 => [:SMACKDOWN, :THOUSANDARROWS]},
		:MOVEACCURACYBOOST => {100 => [:WILLOWISP]},
		:MOVEMESSAGES => {
		"The flames spread from the attack!" => [:SMOG, :CLEARSMOG],
		"{1} was knocked into the flames!" => [:SMACKDOWN, :THOUSANDARROWS]},
		:MOVETYPEMOD => {
		:FIRE => [:SMACKDOWN, :SMOG,
											:CLEARSMOG, :THOUSANDARROWS]},
		:TYPEDAMAGEBOOST => {
		1.5 => [:FIRE],
		0.5 => [:GRASS,:ICE]},
		:TYPEMESSAGES => {
		"The blaze amplified the attack!" => [:FIRE],
    	"The blaze softened the attack..." => [:GRASS,:ICE]},
    	:TYPECONDITION => {
			:FIRE =>  "!attacker.isAirborne?",
			:GRASS => "!opponent.isAirborne?"
		},
		:FIELDCHANGE => {
		0 => PBFields::BLOWMOVES + [:WATERSPORT,:SURF, :MUDDYWATER, 
		:WATERSPOUT, :WATERPLEDGE, :SPARKLINGARIA, 
		:SLUDGEWAVE, :SANDTOMB, :CONTINENTALCRUSH, :HYDROVORTEX, :OCEANICOPERETTA]},
		:CHANGEMESSAGE => {
		"The grime snuffed out the flame!" => [:SLUDGEWAVE],
		"The wind snuffed out the flame!" => PBFields::BLOWMOVES,
		"The water snuffed out the flame!" => [:WATERSPORT,:SURF, 
			:MUDDYWATER, :WATERSPOUT, :WATERPLEDGE, 
			:SPARKLINGARIA, :HYDROVORTEX, :OCEANICOPERETTA],
		"The sand snuffed out the flame!" => [:SANDTOMB, :CONTINENTALCRUSH]},
		:STATUSMOVEBOOST => [:WILLOWISP, :SMOKESCREEN],
		:CHANGEEFFECTS => {},
		:SEED => :ELEMENTALSEED,
		:SEEDEFFECT => :MultiTurnAttack,
		:SEEDEFFECTVAL => :FIRESPIN,
		:SEEDEFFECTSTR => "{1} was trapped in the vortex!",
		:SEEDANIM => :FIRESPIN,
		:SEEDSTATS => {PBStats::ATTACK => 1, PBStats::SPATK => 1, PBStats::SPEED => 1}
		},
	# 8 Swamp Field
	PBFields::SWAMPF => {
		:FIELDNAME => "Swamp Field",
		:INTROMESSAGE => "The field is swamped.",
		:FIELDGRAPHICS =>  "Swamp",
		:SECRETPOWERANIM => :MUDDYWATER,
		:NATUREMOVES => :MUDDYWATER,
		:MIMICRY => :WATER,
		:MOVEDAMAGEBOOST => {
		1.5 => [:MUDBOMB, :MUDSHOT, :MUDSLAP, :MUDDYWATER, 
						:SURF, :SLUDGEWAVE, :GUNKSHOT, :BRINE, 
						:SMACKDOWN, :THOUSANDARROWS, :HYDROVORTEX],
		0.25 => [:EARTHQUAKE, :MAGNITUDE, :BULLDOZE]},
		:MOVEACCURACYBOOST => {100 => [:SLEEPPOWDER]},
		:MOVEMESSAGES => {
		"The murk strengthened the attack!" => [:MUDBOMB, :MUDSHOT, 
			:MUDSLAP, :MUDDYWATER, :SURF, :SLUDGEWAVE, 
			:GUNKSHOT, :BRINE, :SMACKDOWN, :THOUSANDARROWS, :HYDROVORTEX],
		"The attack dissipated in the soggy ground..." => [:EARTHQUAKE, 
			:MAGNITUDE, :BULLDOZE]},
		:MOVETYPEMOD => {:WATER => [:SMACKDOWN, :THOUSANDARROWS]},
		:TYPEDAMAGEBOOST => {1.5 => [:POISON]},
		:TYPEMESSAGES => {"The poison infected the nearby murk!" => [:POISON]},
		:TYPECONDITION => {:POISON => "!opponent.isAirborne?" },
		:STATUSMOVEBOOST => [:SLEEPPOWDER, :AQUARING],
		:CHANGEEFFECTS => {},
		:SEED => :TELLURICSEED,
		:SEEDEFFECT => :Ingrain,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} planted its roots!",
		:SEEDANIM => :INGRAIN,
		:SEEDSTATS => {PBStats::DEFENSE => 1,PBStats::SPDEF => 1}
		},
	# 9 Rainbow Field
	PBFields::RAINBOWF => {
		:FIELDNAME => "Rainbow Field",
		:INTROMESSAGE => "What does it mean?",
		:FIELDGRAPHICS =>  "Rainbow",
		:SECRETPOWERANIM => :AURORABEAM,
		:NATUREMOVES => :AURORABEAM,
		:MIMICRY => :DRAGON,
		:MOVEDAMAGEBOOST => {
		1.5 => [:SILVERWIND, :MYSTICALFIRE, :DRAGONPULSE, 
					:TRIATTACK, :SACREDFIRE, :FIREPLEDGE, 
					:WATERPLEDGE, :GRASSPLEDGE, :AURORABEAM, 
					:JUDGMENT, :RELICSONG, :HIDDENPOWER, 
					:SECRETPOWER, :WEATHERBALL, :MISTBALL, 
					:HEARTSTAMP, :MOONBLAST, :ZENHEADBUTT, 
					:SPARKLINGARIA, :FLEURCANNON, :PRISMATICLASER, :TWINKLETACKLE,
					:OCEANICOPERETTA, :SOLARBEAM, :SOLARBLADE, :DAZZLINGGLEAM,
					:HIDDENPOWERNOR,:HIDDENPOWERFIR,:HIDDENPOWERFIG,:HIDDENPOWERWAT,:HIDDENPOWERFLY,
					:HIDDENPOWERGRA,:HIDDENPOWERPOI,:HIDDENPOWERELE,:HIDDENPOWERGRO,:HIDDENPOWERPSY,
					:HIDDENPOWERROC,:HIDDENPOWERICE,:HIDDENPOWERBUG,:HIDDENPOWERDRA,:HIDDENPOWERGHO,
					:HIDDENPOWERDAR,:HIDDENPOWERSTE,:HIDDENPOWERFAI],
		0.5 => [:DARKPULSE, :SHADOWBALL, :NIGHTDAZE, :NEVERENDINGNIGHTMARE]},
		:MOVEMESSAGES => {
		"The attack was rainbow-charged!" => [:SILVERWIND, :MYSTICALFIRE, 
			:DRAGONPULSE, :TRIATTACK, :SACREDFIRE, :FIREPLEDGE, 
			:WATERPLEDGE, :GRASSPLEDGE, :AURORABEAM, :JUDGMENT, 
			:RELICSONG, :HIDDENPOWER, :SECRETPOWER, :WEATHERBALL, 
			:MISTBALL, :HEARTSTAMP, :MOONBLAST, :ZENHEADBUTT, 
			:SPARKLINGARIA, :FLEURCANNON, :PRISMATICLASER, :TWINKLETACKLE,
			:OCEANICOPERETTA, :SOLARBEAM, :SOLARBLADE, :DAZZLINGGLEAM,
			:HIDDENPOWERNOR,:HIDDENPOWERFIR,:HIDDENPOWERFIG,:HIDDENPOWERWAT,:HIDDENPOWERFLY,
			:HIDDENPOWERGRA,:HIDDENPOWERPOI,:HIDDENPOWERELE,:HIDDENPOWERGRO,:HIDDENPOWERPSY,
			:HIDDENPOWERROC,:HIDDENPOWERICE,:HIDDENPOWERBUG,:HIDDENPOWERDRA,:HIDDENPOWERGHO,
			:HIDDENPOWERDAR,:HIDDENPOWERSTE,:HIDDENPOWERFAI],
		"The rainbow softened the attack..." => [:DARKPULSE, :SHADOWBALL, 
			:NIGHTDAZE, :NEVERENDINGNIGHTMARE]},
		:TYPEDAMAGEBOOST => {1.5 => [:NORMAL]},
		:TYPEMESSAGES => {"The rainbow energized the attack!" => [:NORMAL]},
		:TYPECONDITION => {:NORMAL => "self.pbIsSpecial?(type)" },
		:FIELDCHANGE => {0 => [:LIGHTTHATBURNSTHESKY]},
		:CHANGEMESSAGE => {"The rainbow was consumed!" => [:LIGHTTHATBURNSTHESKY]},
		:STATUSMOVEBOOST => [:COSMICPOWER, :MEDITATE, :WISH],
		:CHANGEEFFECTS => {},
		:SEED => :MAGICALSEED,
		:SEEDEFFECT => :Wish,
		:SEEDEFFECTVAL => 2,
		:SEEDEFFECTSTR => "A wish was made for {1}!",
		:SEEDANIM => :WISH,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 10 Corrosive Field
	PBFields::CORROSIVEF => {
		:FIELDNAME => "Corrosive Field",
		:INTROMESSAGE => "The field is corrupted!",
		:FIELDGRAPHICS =>  "Corrosive",
		:SECRETPOWERANIM => :ACID,
		:NATUREMOVES => :ACIDSPRAY,
		:MIMICRY => :POISON,
		:MOVEDAMAGEBOOST => {
		1.5 => [:SMACKDOWN, :MUDSLAP, :MUDSHOT, :MUDBOMB, 
						:MUDDYWATER, :WHIRLPOOL, :THOUSANDARROWS],
		2.0 => [:ACID, :ACIDSPRAY, :GRASSKNOT]},
		:MOVEACCURACYBOOST => {100 => [:POISONPOWDER, :SLEEPPOWDER, :STUNSPORE, :TOXIC]},
		:MOVEMESSAGES => {
		"The corrosion strengthened the attack!" => [:SMACKDOWN, :MUDSLAP, 
			:MUDSHOT, :MUDBOMB, :MUDDYWATER, :WHIRLPOOL, :THOUSANDARROWS,
			:ACID, :ACIDSPRAY, :GRASSKNOT]},
		:MOVETYPEMOD => {
		:POISON => [:SMACKDOWN, :MUDSLAP, :MUDSHOT, 
			:MUDDYWATER, :WHIRLPOOL, :MUDBOMB, :THOUSANDARROWS]},
		:TYPETYPEMOD => {:POISON => [:GRASS]},
		:FIELDCHANGE => {PBFields::GRASSYT => [:SEEDFLARE]},
		:CHANGEMESSAGE => {"The polluted field was purified!" => [:SEEDFLARE]},
		:STATUSMOVEBOOST => [:ACIDARMOR, :POISONPOWDER, :SLEEPPOWDER, :STUNSPORE, :TOXIC],
		:CHANGEEFFECTS => {},
		:SEED => :TELLURICSEED,
		:SEEDEFFECT => :BanefulBunker,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "The Telluric Seed shielded {1} against damage!",
		:SEEDANIM => :BANEFULBUNKER,
		:SEEDSTATS => {}
		},
	# 11 Corrosive Mist Field
	PBFields::CORROSIVEMISTF => {
		:FIELDNAME => "Corrosive Mist Field",
		:INTROMESSAGE => "Corrosive mist settles on the field!",
		:FIELDGRAPHICS =>  "CorrosiveMist",
		:SECRETPOWERANIM => :ACIDSPRAY,
		:NATUREMOVES => :VENOSHOCK,
		:MIMICRY => :POISON,
		:MOVEDAMAGEBOOST => {
		1.5 => [:BUBBLEBEAM, :ACIDSPRAY, :BUBBLE, :SMOG, 
						:CLEARSMOG, :SPARKLINGARIA]},
		:MOVEACCURACYBOOST => {100 => [:TOXIC]},
		:MOVEMESSAGES => {
		"The poison strengthened the attack!" => [:BUBBLEBEAM, :ACIDSPRAY, 
			:BUBBLE, :SMOG, :CLEARSMOG, :SPARKLINGARIA]},
		:MOVETYPEMOD => {
		:POISON => [:BUBBLE, :BUBBLEBEAM,
			:ENERGYBALL, :SPARKLINGARIA]},
		:TYPEDAMAGEBOOST => {1.5 => [:FIRE]},
		:TYPEMESSAGES => {"The toxic mist caught flame!" => [:FIRE]},
		:FIELDCHANGE => {
		0 => PBFields::BLOWMOVES + PBFields::IGNITEMOVES + [:SELFDESTRUCT, :EXPLOSION] + [:SEEDFLARE],
		PBFields::CORROSIVEF => [:GRAVITY]},
		:DONTCHANGEBACKUP => [:GRAVITY],
		:CHANGEMESSAGE => {
		#"The toxic mist combusted!" => PBFields::IGNITEMOVES + [:SELFDESTRUCT, :EXPLOSION],
		"The mist was blown away!" => PBFields::BLOWMOVES,
		"The polluted mist was purified!" => [:SEEDFLARE],
		"The toxic mist collected on the ground!" => [:GRAVITY]},
		:STATUSMOVEBOOST => [:ACIDARMOR],
		:CHANGEEFFECTS => {},
		:SEED => :ELEMENTALSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1} was badly poisoned!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::ATTACK => 1, PBStats::SPATK => 1}
		},
	# 12 Desert Field
	PBFields::DESERTF => {
		:FIELDNAME => "Desert Field",
		:INTROMESSAGE => "The field is rife with sand.",
		:FIELDGRAPHICS =>  "Desert",
		:SECRETPOWERANIM => :SANDTOMB,
		:NATUREMOVES => :SANDTOMB,
		:MIMICRY => :GROUND,
		:MOVEDAMAGEBOOST => {
		1.5 => [:NEEDLEARM, :PINMISSILE, :DIG, :SANDTOMB, 
						:HEATWAVE, :THOUSANDWAVES, :BURNUP, :SEARINGSUNRAZESMASH,
						:SOLARBLADE, :SOLARBEAM]},
		:MOVEMESSAGES => {
		"The desert strengthened the attack!" => [:NEEDLEARM, :PINMISSILE, 
			:DIG, :SANDTOMB, :HEATWAVE, :THOUSANDWAVES, 
			:BURNUP, :SEARINGSUNRAZESMASH, :SOLARBLADE, :SOLARBEAM]},
		:TYPEDAMAGEBOOST => {0.5 => [:WATER,:ELECTRIC]},
		:TYPEMESSAGES => {"The desert softened the attack..." => [:WATER,:ELECTRIC]},
		:TYPECONDITION => {
			:WATER => "!attacker.isAirborne?" ,
			:ELECTRIC => "!opponent.isAirborne?" },
		:STATUSMOVEBOOST => [:SANDSTORM, :SUNNYDAY, :SANDATTACK, :SHOREUP],
		:CHANGEEFFECTS => {},
		:SEED => :TELLURICSEED,
		:SEEDEFFECT => :MultiTurnAttack,
		:SEEDEFFECTVAL => :SANDTOMB,
		:SEEDEFFECTSTR => "{1} was trapped by Sand Tomb!",
		:SEEDANIM => :SANDTOMB,
		:SEEDSTATS => {PBStats::DEFENSE => 1, PBStats::SPDEF => 1, PBStats::SPEED => 1}
		},
	# 13 Icy Field
	PBFields::ICYF => {
		:FIELDNAME => "Icy Field",
		:INTROMESSAGE => "The field is covered in ice.",
		:FIELDGRAPHICS =>  "Icy",
		:SECRETPOWERANIM => :ICESHARD,
		:NATUREMOVES => :ICEBEAM,
		:MIMICRY => :ICE,
		:MOVEDAMAGEBOOST => { 0.5 => [:SCALD, :STEAMERUPTION]},
		:MOVEMESSAGES => {"The cold softened the attack..." => [:SCALD, :STEAMERUPTION]},
		:TYPEDAMAGEBOOST => {
		1.5 => [:ICE],
		0.5 => [:FIRE]},
		:TYPEMESSAGES => {
		"The cold strengthened the attack!" => [:ICE],
		"The cold softened the attack..." => [:FIRE]},
		:TYPETYPEMOD => {:ICE => [:ROCK]},
		:FIELDCHANGE => {PBFields::WATERS => PBFields::IGNITEMOVES},
		:CHANGEMESSAGE => {"The ice melted away!" => PBFields::IGNITEMOVES},
		:STATUSMOVEBOOST => [:HAIL],
		:STATUSMOVEBOOST => [:ACIDARMOR],
		:CHANGEEFFECTS => {},
		:SEED => :ELEMENTALSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1} was hurt by icy Spikes!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::SPEED => 2}
		},
	# 14 Rocky Field
	PBFields::ROCKYF => {
		:FIELDNAME => "Rocky Field",
		:INTROMESSAGE => "The field is littered with rocks.",
		:FIELDGRAPHICS =>  "Rocky",
		:SECRETPOWERANIM => :ROCKTHROW,
		:NATUREMOVES => :ROCKSMASH,
		:MIMICRY => :ROCK,
		:MOVEDAMAGEBOOST => {
		1.5 => [:ROCKCLIMB, :STRENGTH, :MAGNITUDE, 
						:EARTHQUAKE, :BULLDOZE, :ACCELEROCK],
		2.0 => [:ROCKSMASH]},
		:MOVEMESSAGES => {
		"The rocks strengthened the attack!" => [:ROCKCLIMB, :STRENGTH, 
			:MAGNITUDE, :EARTHQUAKE, :BULLDOZE, :ACCELEROCK],
		"SMASH'D!" => [:ROCKSMASH]},
		:MOVETYPEMOD => {
		:ROCK => [:ROCKCLIMB, :EARTHQUAKE, :MAGNITUDE, 
			:STRENGTH, :BULLDOZE]},
		:TYPEDAMAGEBOOST => {1.5 => [:ROCK]},
		:TYPEMESSAGES => {"The field strengthened the attack!" => [:ROCK]},
		:STATUSMOVEBOOST => [:ROCKPOLISH],
		:CHANGEEFFECTS => {},
		:SEED => :TELLURICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1} was hurt by Stealth Rocks!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::DEFENSE => 1}
		},
	# 15 Forest Field
	PBFields::FORESTF => {
		:FIELDNAME => "Forest Field",
		:INTROMESSAGE => "The field is abound with trees.",
		:FIELDGRAPHICS =>  "Forest",
		:SECRETPOWERANIM => :WOODHAMMER,
		:NATUREMOVES => :WOODHAMMER,
		:MIMICRY => :GRASS,
		:MOVEDAMAGEBOOST => {
		0.5 => [:SURF, :MUDDYWATER],
		1.5 => [:ATTACKORDER, :ELECTROWEB, :CUT]},
		:MOVEMESSAGES => {
		"The forest softened the attack..." => [:SURF, :MUDDYWATER],
		"They're coming out of the woodwork!" => [:ATTACKORDER],
		"Gossamer and arbor strengthened the attack!" => [:ELECTROWEB],
		"The target was cut down to size!" => [:CUT]},
		:TYPEDAMAGEBOOST => {1.5 => [:BUG,:GRASS]},
		:TYPEMESSAGES => {
		"The field strengthened the attack!" => [:BUG],
		"The forestry strengthened the attack!" => [:GRASS]},
		:TYPECONDITION => {:BUG => "self.pbIsSpecial?(type)" },
		:FIELDCHANGE => {PBFields::BURNINGF => PBFields::IGNITEMOVES},
		:DONTCHANGEBACKUP => PBFields::IGNITEMOVES,
		:CHANGEMESSAGE => {"The forest caught fire!" => PBFields::IGNITEMOVES},
		:CHANGECONDITION => {PBFields::BURNINGF => "ignitecheck"},
		:STATUSMOVEBOOST => [:STICKYWEB, :DEFENDORDER, :GROWTH,
		 	:STRENGTHSAP, :HEALORDER, :NATURESMADNESS, :FORESTSCURSE],
		:CHANGEEFFECTS => {},
		:SEED => :TELLURICSEED,
		:SEEDEFFECT => :SpikyShield,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "The Telluric Seed shielded {1} against damage!",
		:SEEDANIM => :SPIKYSHIELD,
		:SEEDSTATS => {}
		},
	# 16 Superheated Field
	PBFields::SUPERHEATEDF => {
		:FIELDNAME => "Super-Heated Field",
		:INTROMESSAGE => "The field is super-heated!",
		:FIELDGRAPHICS =>  "Superheated",
		:SECRETPOWERANIM => :FLAMEBURST,
		:NATUREMOVES => :HEATWAVE,
		:MIMICRY => :FIRE,
		:MOVEDAMAGEBOOST => {
		0.625 => [:SURF, :MUDDYWATER, :WATERPLEDGE, 
							:WATERSPOUT, :SPARKLINGARIA, :HYDROVORTEX, :OCEANICOPERETTA],
		1.667 => [:SCALD, :STEAMERUPTION]},
		:MOVEMESSAGES => {
		#"cass couldn't find this message. make ame fix it." => [:SURF, :MUDDYWATER, :WATERPLEDGE, 
		#		:WATERSPOUT, :SPARKLINGARIA, :HYDROVORTEX, :OCEANICOPERETTA],
		#This message is handled elsewhere, "Steam shot up from the field!"
		"The field super-heated the attack!" => [:SCALD, :STEAMERUPTION]},
		:TYPEDAMAGEBOOST => {
		0.5 => [:ICE],
		0.9 => [:WATER],
		1.1 => [:FIRE]},
		:TYPEMESSAGES => {
		"The extreme heat softened the attack..." => [:ICE,:WATER],
		"The attack was super-heated!" => [:FIRE]},
		:FIELDCHANGE => {
		PBFields::BURNINGF => PBFields::IGNITEMOVES + [:SELFDESTRUCT, :EXPLOSION],
		0 => [:BLIZZARD, :GLACIATE, :SUBZEROSLAMMER]},
		:DONTCHANGEBACKUP => PBFields::IGNITEMOVES + [:SELFDESTRUCT, :EXPLOSION],
		:CHANGEMESSAGE => {
		"The field combusted!" => PBFields::IGNITEMOVES + [:SELFDESTRUCT, :EXPLOSION],
		"The field cooled off!"=> [:BLIZZARD, :GLACIATE, :SUBZEROSLAMMER]},
		:CHANGECONDITION => {PBFields::BURNINGF => "ignitecheck"},
		:STATUSMOVEBOOST => [],
		:CHANGEEFFECTS => {},
		:SEED => :TELLURICSEED,
		:SEEDEFFECT => :ShellTrap,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} primed a trap!",
		:SEEDANIM => :SHELLTRAP,
		:SEEDSTATS => {PBStats::DEFENSE => 1}
		},
	# 17 Factory Field
	PBFields::FACTORYF => {
		:FIELDNAME => "Factory Field",
		:INTROMESSAGE => "Machines whir in the background.",
		:FIELDGRAPHICS =>  "Factory",
		:SECRETPOWERANIM => :MAGNETBOMB,
		:NATUREMOVES => :GEARGRIND,
		:MIMICRY => :STEEL,
		:MOVEDAMAGEBOOST => {
		1.5 => [:STEAMROLLER, :TECHNOBLAST],
		2.0 => [:FLASHCANNON, :GYROBALL, :MAGNETBOMB, :GEARGRIND]},
		:MOVEMESSAGES => {
		"ATTACK SEQUENCE UPDATE." => [:STEAMROLLER, :TECHNOBLAST],
		"ATTACK SEQUENCE INITIATE." => [:FLASHCANNON, :GYROBALL, 
			:MAGNETBOMB, :GEARGRIND]},
		:TYPEDAMAGEBOOST => {1.5 => [:ELECTRIC]},
		:TYPEMESSAGES => {"The attack took energy from the field!" => [:ELECTRIC]},
		:FIELDCHANGE => {
		PBFields::SHORTCIRCUITF => PBFields::QUAKEMOVES + [:SELFDESTRUCT, :EXPLOSION, :LIGHTTHATBURNSTHESKY]},
		:CHANGEMESSAGE => {
		"The field was broken!" => PBFields::QUAKEMOVES + [:SELFDESTRUCT, :EXPLOSION],
		"All the light was consumed!" => [:LIGHTTHATBURNSTHESKY]},
		:STATUSMOVEBOOST => [:AUTOTOMIZE, :IRONDEFENSE, :METALSOUND, :SHIFTGEAR, :MAGNETRISE, :GEARUP],
		:CHANGEEFFECTS => {},
		:SEED => :SYNTHETICSEED,
		:SEEDEFFECT => :LaserFocus,
		:SEEDEFFECTVAL => 1,
		:SEEDEFFECTSTR => "{1} is focused!",
		:SEEDANIM => :LASERFOCUS,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 18 Short-Circuit Field
	PBFields::SHORTCIRCUITF => {
		:FIELDNAME => "Short-Circuit Field",
		:INTROMESSAGE => "Bzzt!",
		:FIELDGRAPHICS =>  "Shortcircuit",
		:SECRETPOWERANIM => :ELECTROBALL,
		:NATUREMOVES => :DISCHARGE,
		:MIMICRY => :ELECTRIC,
		:MOVEDAMAGEBOOST => {
		1.5 => [:DAZZLINGGLEAM, :SURF, :MUDDYWATER, :MAGNETBOMB,
						:GYROBALL, :FLASHCANNON, :GEARGRIND, :HYDROVORTEX],
		1.3 => [:DARKPULSE, :NIGHTDAZE, :NIGHTSLASH, 
						:SHADOWBALL, :SHADOWPUNCH, :SHADOWCLAW,
						:SHADOWSNEAK, :SHADOWFORCE, :SHADOWBONE],
		0.5 => [:LIGHTTHATBURNSTHESKY]},
		:MOVEACCURACYBOOST => {80 => [:ZAPCANNON]},
		:MOVEMESSAGES => {
		"Blinding!" => [:DAZZLINGGLEAM], 
		"The attack picked up electricity!" => [:SURF, :MUDDYWATER, 
			:MAGNETBOMB, :GYROBALL, :FLASHCANNON, :GEARGRIND, :HYDROVORTEX],
		"The darkness strengthened the attack!" => [:DARKPULSE, :NIGHTDAZE, 
			:NIGHTSLASH, :SHADOWBALL, :SHADOWPUNCH, :SHADOWCLAW, 
			:SHADOWSNEAK, :SHADOWFORCE, :SHADOWBONE],
		"{1} couldn't consume much light..." => [:LIGHTTHATBURNSTHESKY]},
		:MOVETYPEMOD => {
		:ELECTRIC => [:SURF, :MUDDYWATER, :MAGNETBOMB, 
			:GYROBALL, :FLASHCANNON, :GEARGRIND]},
		:FIELDCHANGE => {PBFields::FACTORYF => [:PARABOLICCHARGE, :WILDCHARGE,
											:CHARGEBEAM, :IONDELUGE, :GIGAVOLTHAVOC]},
		:CHANGEMESSAGE => {"SYSTEM ONLINE." => [:PARABOLICCHARGE, :WILDCHARGE, 
												:CHARGEBEAM, :IONDELUGE, :GIGAVOLTHAVOC]},
		:STATUSMOVEBOOST => [:FLASH, :METALSOUND, :MAGNETRISE],
		:CHANGEEFFECTS => {},
		:SEED => :SYNTHETICSEED,
		:SEEDEFFECT => :MagnetRise,
		:SEEDEFFECTVAL => 5,
		:SEEDEFFECTSTR => "{1} levitated with electromagnetism!",
		:SEEDANIM => :MAGNETRISE,
		:SEEDSTATS => {PBStats::SPDEF => 1}
		},
	# 19 Wasteland
	PBFields::WASTELAND => {
		:FIELDNAME => "Wasteland",
		:INTROMESSAGE => "The waste is watching...",
		:FIELDGRAPHICS =>  "Wasteland",
		:SECRETPOWERANIM => :GUNKSHOT,
		:NATUREMOVES => :GUNKSHOT,
		:MIMICRY => :POISON,
		:MOVEDAMAGEBOOST => {
		1.5 => [:VINEWHIP, :POWERWHIP, :MUDSLAP, 
						:MUDBOMB, :MUDSHOT],
		0.25 => [:EARTHQUAKE, :MAGNITUDE, :BULLDOZE],
		2.0 => [:SPITUP],
		1.2 => [:OCTAZOOKA, :SLUDGE, :GUNKSHOT, 
						:SLUDGEWAVE, :SLUDGEBOMB]},
		:MOVEMESSAGES => {
		"The waste did it for the vine!" => [:VINEWHIP, :POWERWHIP], 
		"The waste was added to the attack!" => [:MUDSLAP, :MUDBOMB, :MUDSHOT],
		"Wibble-wibble wobble-wobb..." => [:EARTHQUAKE, :MAGNITUDE, :BULLDOZE],
		"BLEAAARGGGGH!" => [:SPITUP],
		"The waste joined the attack!" => [:OCTAZOOKA, :SLUDGE, :GUNKSHOT, 
			:SLUDGEWAVE, :SLUDGEBOMB]},
		:MOVETYPEMOD => {
		:POISON => [:MUDBOMB, :MUDSLAP, :MUDSHOT]},
		:STATUSMOVEBOOST => [:SWALLOW],
		:CHANGEEFFECTS => {},
		:SEED => :TELLURICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::ATTACK => 1, PBStats::SPATK => 1}
		},
	# 20 Ashen Beach
	PBFields::ASHENB => {
		:FIELDNAME => "Ashen Beach",
		:INTROMESSAGE => "Ash and sand line the field.",
		:FIELDGRAPHICS =>  "AshenBeach",
		:SECRETPOWERANIM => :MUDSHOT,
		:NATUREMOVES => :MEDITATE,
		:MIMICRY => :GROUND,
		:MOVEDAMAGEBOOST => {
		1.5 => [:HIDDENPOWER, :STRENGTH, :LANDSWRATH, 
						:THOUSANDWAVES, :SURF, :MUDDYWATER, :CLANGOROUSSOULBLAZE,
						:HIDDENPOWERNOR,:HIDDENPOWERFIR,:HIDDENPOWERFIG,:HIDDENPOWERWAT,:HIDDENPOWERFLY,
						:HIDDENPOWERGRA,:HIDDENPOWERPOI,:HIDDENPOWERELE,:HIDDENPOWERGRO,:HIDDENPOWERPSY,
						:HIDDENPOWERROC,:HIDDENPOWERICE,:HIDDENPOWERBUG,:HIDDENPOWERDRA,:HIDDENPOWERGHO,
						:HIDDENPOWERDAR,:HIDDENPOWERSTE,:HIDDENPOWERFAI],
		2.0 => [:MUDSLAP, :MUDSHOT, :MUDBOMB , :SANDTOMB],
		1.3 => [:STOREDPOWER, :ZENHEADBUTT, 
						:FOCUSBLAST, :AURASPHERE],
		1.2 => [:PSYCHIC]},
		:MOVEACCURACYBOOST => {90 => [:FOCUSBLAST]},
		:MOVEMESSAGES => {
		"...And with pure focus!" => [:HIDDENPOWER, :STRENGTH, :CLANGOROUSSOULBLAZE,
		:HIDDENPOWERNOR,:HIDDENPOWERFIR,:HIDDENPOWERFIG,:HIDDENPOWERWAT,:HIDDENPOWERFLY,
		:HIDDENPOWERGRA,:HIDDENPOWERPOI,:HIDDENPOWERELE,:HIDDENPOWERGRO,:HIDDENPOWERPSY,
		:HIDDENPOWERROC,:HIDDENPOWERICE,:HIDDENPOWERBUG,:HIDDENPOWERDRA,:HIDDENPOWERGHO,
		:HIDDENPOWERDAR,:HIDDENPOWERSTE,:HIDDENPOWERFAI], 
		"The sand strengthened the atttack!" => [:LANDSWRATH, :THOUSANDWAVES], 
		"Surf's up!" => [:SURF, :MUDDYWATER],
		"Ash mixed into the attack!" => [:MUDSLAP, :MUDSHOT, :MUDBOMB , :SANDTOMB],
		"...And with full focus...!" => [:STOREDPOWER, :ZENHEADBUTT, 
			:FOCUSBLAST, :AURASPHERE],
		"...And with focus...!" => [:PSYCHIC]},
		:MOVETYPEMOD => {:PSYCHIC => [:STRENGTH]},
		:STATUSMOVEBOOST => [:CALMMIND, :KINESIS, :MEDITATE, :SANDATTACK,
			:SANDSTORM, :FOCUSENERGY, :SHOREUP],
		:CHANGEEFFECTS => {},
		:SEED => :TELLURICSEED,
		:SEEDEFFECT => :FocusEnergy,
		:SEEDEFFECTVAL => 3,
		:SEEDEFFECTSTR => "{1}'s Telluric Seed is getting it pumped!",
		:SEEDANIM => :FOCUSENERGY,
		:SEEDSTATS => {}
		},
	# 21 Water Surface
	PBFields::WATERS => {
		:FIELDNAME => "Water Surface",
		:INTROMESSAGE => "The water's surface is calm.",
		:FIELDGRAPHICS =>  "WaterSurface",
		:SECRETPOWERANIM => :AQUAJET,
		:NATUREMOVES => :WHIRLPOOL,
		:MIMICRY => :WATER,
		:MOVEDAMAGEBOOST => {
			1.5 => [:SURF, :MUDDYWATER, :WHIRLPOOL, :DIVE, :HYDROVORTEX]},
		:MOVEMESSAGES => {
			"The attack rode the current!" => [:SURF, :MUDDYWATER, 
				:WHIRLPOOL, :DIVE, :HYDROVORTEX]},
		:TYPEDAMAGEBOOST => {
			1.5 => [:WATER,:ELECTRIC],
			0.5 => [:FIRE]},
		:TYPEMESSAGES => {
			"The water conducted the attack!" => [:ELECTRIC],
			"The water strengthened the attack!" => [:WATER],
			"The water deluged the attack..." => [:FIRE]},
		:TYPECONDITION => {
			:FIRE => "!opponent.isAirborne?" ,
			:ELECTRIC => "!opponent.isAirborne?" },
		:FIELDCHANGE => {
			PBFields::UNDERWATER => [:GRAVITY,:DIVE],
			PBFields::ICYF => [:BLIZZARD, :GLACIATE, :SUBZEROSLAMMER]},
		:DONTCHANGEBACKUP => [:BLIZZARD, :GLACIATE, :SUBZEROSLAMMER],
		:CHANGEMESSAGE => {
			"The battle sank into the depths!" => [:GRAVITY],
			"The battle was pulled underwater!" => [:DIVE],
			"The water froze over!" => [:BLIZZARD, :GLACIATE, :SUBZEROSLAMMER]},
		:STATUSMOVEBOOST => [:SPLASH, :AQUARING],
		:CHANGEEFFECTS => {},
		:SEED => :ELEMENTALSEED,
		:SEEDEFFECT => :AquaRing,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} surrounded itself with a veil of water!",
		:SEEDANIM => :AQUARING,
		:SEEDSTATS => {PBStats::SPDEF => 1}
		},
	# 22 Underwater
	PBFields::UNDERWATER => {
		:FIELDNAME => "Underwater",
		:INTROMESSAGE => "Blub blub...",
		:FIELDGRAPHICS =>  "Underwater",
		:SECRETPOWERANIM => :AQUATAIL,
		:NATUREMOVES => :WATERPULSE,
		:MIMICRY => :WATER,
		:MOVEDAMAGEBOOST => {
		1.5 => [:WATERPULSE],
		2.0 => [:ANCHORSHOT]},
		:MOVEMESSAGES => {
			"Jet-streamed!" => [:WATERPULSE],
			"From the depths!" => [:ANCHORSHOT]},
		:TYPETYPEMOD => {:WATER => [:GROUND]},
		:TYPEDAMAGEBOOST => {
		1.5 => [:WATER],
		2.0 => [:ELECTRIC]},
		:TYPEMESSAGES => {
		"The water strengthened the attack!" => [:WATER],
		"The water super-conducted the attack!" => [:ELECTRIC]},
		:FIELDCHANGE => {PBFields::WATERS => [:DIVE, :SKYDROP, :FLY, :BOUNCE]},
		:CHANGEMESSAGE => {"The battle resurfaced!" => [:DIVE, 
			:SKYDROP, :FLY, :BOUNCE]},
		:STATUSMOVEBOOST => [:AQUARING],
		:CHANGEEFFECTS => {},
		:SEED => :ELEMENTALSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1} transformed into the Water type!",
		:SEEDANIM => :SOAK,
		:SEEDSTATS => {PBStats::SPEED => 1}
		},
	# 23 Cave
	PBFields::CAVE => {
		:FIELDNAME => "Cave",
		:INTROMESSAGE => "The cave echoes dully...",
		:FIELDGRAPHICS =>  "Cave",
		:SECRETPOWERANIM => :ROCKWRECKER,
		:NATUREMOVES => :ROCKTOMB,
		:MIMICRY => :ROCK,
		:MOVEDAMAGEBOOST => {1.5 => [:ROCKTOMB]},
		:MOVEMESSAGES => {"...Piled on!" => [:ROCKTOMB]},
		:TYPEDAMAGEBOOST => {
			1.5 => [:ROCK],
			0.5 => [:FLYING]},
		:TYPEMESSAGES => {
		"The cave choked out the air!" => [:FLYING],
		"The cavern strengthened the attack!" => [:ROCK]},
		:TYPECONDITION => {:FLYING => "!self.contactMove?" },
		:FIELDCHANGE => {
			PBFields::CRYSTALC => [:POWERGEM, :DIAMONDSTORM],
			PBFields::CAVE => PBFields::QUAKEMOVES + [:CONTINENTALCRUSH]},
		:DONTCHANGEBACKUP => [:POWERGEM, :DIAMONDSTORM],
		:CHANGEMESSAGE => {"The cave was littered with crystals!" => [:POWERGEM, :DIAMONDSTORM]},
		:CHANGECONDITION => {},
		:STATUSMOVEBOOST => [:STEALTHROCK],
		:CHANGEEFFECTS => {},
		:SEED => :TELLURICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1} was hurt by Stealth Rocks!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::DEFENSE => 2}
		},
	# 24 Glitch Field
	PBFields::GLITCHF => {
		:FIELDNAME => "Glitch Field",
		:INTROMESSAGE => "1n!taliz3 .b//////attl3",
		:FIELDGRAPHICS =>  "Glitch",
		:SECRETPOWERANIM => :TECHNOBLAST,
		:NATUREMOVES => :METRONOME,
		:MIMICRY => :QMARKS,
		:MOVEDAMAGEBOOST => {},
		:MOVEACCURACYBOOST => {90 => [:BLIZZARD]},
		:MOVEMESSAGES => {},
		:TYPEDAMAGEBOOST => {1.2 => [:PSYCHIC]},
		:TYPEMESSAGES => {".0P pl$ nerf!-//" => [:PSYCHIC]},
		:STATUSMOVEBOOST => [],
		:CHANGEEFFECTS => {},
		:SEED => :SYNTHETICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1}.TYPE = (:QMARKS)",
		:SEEDANIM => :AMNESIA,
		:SEEDSTATS => {PBStats::DEFENSE => 1}
		},
	# 25 Crystal Cavern
	PBFields::CRYSTALC => {
		:FIELDNAME => "Crystal Cavern",
		:INTROMESSAGE => "The cave is littered with crystals.",
		:FIELDGRAPHICS =>  "CrystalCavern",
		:SECRETPOWERANIM => :POWERGEM,
		:NATUREMOVES => :POWERGEM,
		:MIMICRY => :QMARKS, #RNG
		:MOVEDAMAGEBOOST => {
		1.3 => [:AURORABEAM, :SIGNALBEAM, :FLASHCANNON, 
						:LUSTERPURGE, :DAZZLINGGLEAM, :MIRRORSHOT, 
						:TECHNOBLAST, :DOOMDUMMY, :MOONGEISTBEAM, 
						:PHOTONGEYSER, :MENACINGMOONRAZEMAELSTROM],
		1.5 => [:POWERGEM, :DIAMONDSTORM, :ANCIENTPOWER, 
						:JUDGMENT, :ROCKSMASH, :ROCKTOMB, :STRENGTH, 
						:ROCKCLIMB, :MULTIATTACK]},
		:MOVEMESSAGES => {
		"The crystals' light strengthened the attack!" => [:AURORABEAM, 
			:SIGNALBEAM, :FLASHCANNON, :LUSTERPURGE, 
			:DAZZLINGGLEAM, :MIRRORSHOT, :TECHNOBLAST, 
			:DOOMDUMMY, :MOONGEISTBEAM, :PHOTONGEYSER,
			:MENACINGMOONRAZEMAELSTROM],
		"The crystals strengthened the attack!" => [:POWERGEM, :DIAMONDSTORM, 
			:ANCIENTPOWER, :JUDGMENT, :ROCKSMASH, :ROCKTOMB, 
			:STRENGTH, :ROCKCLIMB, :MULTIATTACK]},
		:TYPEDAMAGEBOOST => {1.5 => [:ROCK,:DRAGON]},
		:TYPEMESSAGES => {
			"The crystals charged the attack!" => [:ROCK],
			"The crystal energy strengthened the attack!" => [:DRAGON]},
		:FIELDCHANGE => {
			PBFields::CAVE => PBFields::QUAKEMOVES,
			PBFields::DARKCRYSTALC => [:DARKPULSE, :DARKVOID, :NIGHTDAZE, :LIGHTTHATBURNSTHESKY]},
		:DONTCHANGEBACKUP => PBFields::QUAKEMOVES + [:DARKPULSE, :DARKVOID, :NIGHTDAZE],
		:CHANGEMESSAGE => {
			"The crystals were broken up!" => PBFields::QUAKEMOVES,
			"The crystals' light was warped by the darkness!" => [:DARKPULSE, 
				:DARKVOID, :NIGHTDAZE],
			"The crystals' light was consumed!" => [:LIGHTTHATBURNSTHESKY]},
		:STATUSMOVEBOOST => [:ROCKPOLISH, :STEALTHROCK],
		:CHANGEEFFECTS => {},
		:SEED => :MAGICALSEED,
		:SEEDEFFECT => :MagicCoat,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} shrouded itself with Magic Coat!",
		:SEEDANIM => :MAGICCOAT,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 26 Murkwater Surface
	PBFields::MURKWATERS => {
		:FIELDNAME => "Murkwater Surface",
		:INTROMESSAGE => "The water is tainted...",
		:FIELDGRAPHICS =>  "MurkwaterSurface",
		:SECRETPOWERANIM => :SLUDGEBOMB,
		:NATUREMOVES => :SLUDGEWAVE,
		:MIMICRY => :POISON,
		:MOVEDAMAGEBOOST => {
		1.5 => [:MUDBOMB, :MUDSLAP, :MUDSHOT, :SMACKDOWN, 
						:ACID, :ACIDSPRAY, :BRINE, :THOUSANDWAVES]},
		:MOVEMESSAGES => {
		"The toxic water strengthened the attack!" => [:MUDBOMB, :MUDSLAP, 
			:MUDSHOT, :SMACKDOWN, :ACID, :ACIDSPRAY, :THOUSANDWAVES],
		"Stinging!" => [:BRINE]},
		:MOVETYPEMOD => {
		:POISON => [:MUDBOMB, :MUDSLAP, :MUDSHOT, 
												:SMACKDOWN, :THOUSANDWAVES],
		:WATER => [:SLUDGEWAVE]},
		:TYPETYPEMOD => {:POISON => [:WATER]},
		:TYPEDAMAGEBOOST => {
			1.5 => [:WATER,:POISON],
			1.3 => [:ELECTRIC],
		},
		:TYPEMESSAGES => {
		"The toxic water strengthened the attack!" => [:WATER,:POISON],
		"The toxic water conducted the attack!" => [:ELECTRIC]},
		:TYPECONDITION => {
			:ELECTRIC => "!opponent.isAirborne?",
		},
		:FIELDCHANGE => {
		PBFields::WATERS => [:WHIRLPOOL],
		PBFields::ICYF => [:BLIZZARD, :GLACIATE,:SUBZEROSLAMMER]},
		:DONTCHANGEBACKUP => [:WHIRLPOOL,:BLIZZARD, :GLACIATE,:SUBZEROSLAMMER],
		:CHANGEMESSAGE => {
		"The maelstrom flushed out the poison!" => [:WHIRLPOOL],
		"The toxic water froze over!" => [:BLIZZARD, :GLACIATE,:SUBZEROSLAMMER]},
		:STATUSMOVEBOOST => [:ACIDARMOR],
		:CHANGEEFFECTS => {},
		:SEED => :ELEMENTALSEED,
		:SEEDEFFECT => :AquaRing,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} surrounded itself with a veil of water!",
		:SEEDANIM => :AQUARING,
		:SEEDSTATS => {PBStats::SPEED => 1}
		},
	# 27 Mountain
	PBFields::MOUNTAIN => {
		:FIELDNAME => "Mountain",
		:INTROMESSAGE => ["Adieu to disappointment and spleen,","What are men to rocks and mountains?"], #oh good, i hate spleen
		:FIELDGRAPHICS =>  "Mountain",
		:SECRETPOWERANIM => :ROCKBLAST,
		:NATUREMOVES => :ROCKSLIDE,
		:MIMICRY => :ROCK,
		:MOVEDAMAGEBOOST => {
		1.5 => [:VITALTHROW, :CIRCLETHROW, :STORMTHROW, 
						:OMINOUSWIND, :ICYWIND, :SILVERWIND, :TWISTER, 
						:RAZORWIND, :FAIRYWIND, :THUNDER, :ERUPTION, 
						:AVALANCHE, :HYPERVOICE]},
		:MOVEMESSAGES => {
		"{1} was thrown partway down the mountain!" => [:VITALTHROW, 
			:CIRCLETHROW, :STORMTHROW],
		"The wind strengthened the attack!" => [:OMINOUSWIND, :ICYWIND, 
			:SILVERWIND, :TWISTER, :RAZORWIND, :FAIRYWIND], 
		"The mountain strengthened the attack!" => [:THUNDER, 
			:ERUPTION, :AVALANCHE],
		"Yodelayheehoo~" => [:HYPERVOICE]},
		:TYPEDAMAGEBOOST => {1.5 => [:ROCK,:FLYING]},
		:TYPEMESSAGES => {
		"The mountain strengthened the attack!" => [:ROCK],
		"The open air strengthened the attack!" => [:FLYING]},
		:FIELDCHANGE => {PBFields::SNOWYM => [:BLIZZARD, :GLACIATE,:SUBZEROSLAMMER]},
		:DONTCHANGEBACKUP => [:BLIZZARD, :GLACIATE,:SUBZEROSLAMMER],
		:CHANGEMESSAGE => {"The mountain was covered in snow!" => [:BLIZZARD, :GLACIATE,:SUBZEROSLAMMER]},
		:STATUSMOVEBOOST => [:TAILWIND, :SUNNYDAY],
		:CHANGEEFFECTS => {},
		:SEED => :TELLURICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::ATTACK => 2, PBStats::ACCURACY => -1}
		},
	# 28 Snowy Mountain
	PBFields::SNOWYM => {
		:FIELDNAME => "Snowy Mountain",
		:INTROMESSAGE => "The snow glows white on the mountain...",
		:FIELDGRAPHICS =>  "SnowyMountain",
		:SECRETPOWERANIM => :ICEBALL,
		:NATUREMOVES => :AVALANCHE,
		:MIMICRY => :ICE,
		:MOVEDAMAGEBOOST => {
		1.5 => [:VITALTHROW, :CIRCLETHROW, :STORMTHROW, 
						:OMINOUSWIND, :SILVERWIND, :TWISTER, :RAZORWIND, 
						:FAIRYWIND, :AVALANCHE, :POWDERSNOW, :HYPERVOICE,
						:GLACIATE],
		0.5 => [:SCALD, :STEAMERUPTION],
		2.0 => [:ICYWIND]},
		:MOVEMESSAGES => {
		"{1} was thrown partway down the mountain!" => [:VITALTHROW, 
			:CIRCLETHROW, :STORMTHROW],
		"The wind strengthened the attack!" => [:OMINOUSWIND, :SILVERWIND, 
			:TWISTER, :RAZORWIND, :FAIRYWIND], 
		"The snow strengthened the attack!" => [:AVALANCHE, :POWDERSNOW],
		"The cold softened the attack..." => [:SCALD, :STEAMERUPTION],
		"The frigid wind strengthened the attack!" => [:ICYWIND],
		"Yodelayheehoo~" => [:HYPERVOICE]},
		:TYPETYPEMOD => {:ICE => [:ROCK]},
		:TYPEDAMAGEBOOST => {
		1.5 => [:ROCK,:ICE,:FLYING],
		0.5 => [:FIRE]},
		:TYPEMESSAGES => {
		"The snowy mountain strengthened the attack!" => [:ROCK,:ICE],
		"The open air strengthened the attack!" => [:FLYING],
		"The cold softened the attack!" => [:FIRE]},
		:FIELDCHANGE => {PBFields::MOUNTAIN => PBFields::IGNITEMOVES},
		:CHANGEMESSAGE => {"The snow melted away!" => PBFields::IGNITEMOVES},
		:STATUSMOVEBOOST => [:TAILWIND, :SUNNYDAY, :HAIL],
		:CHANGEEFFECTS => {},
		:SEED => :TELLURICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::SPATK => 2, PBStats::ACCURACY => -1}
		},
	# 29 Holy Field
	PBFields::HOLYF => {
		:FIELDNAME => "Holy Field",
		:INTROMESSAGE => "Benedictus Sanctus Spiritus...",
		:FIELDGRAPHICS =>  "Holy",
		:SECRETPOWERANIM => :DAZZLINGGLEAM,
		:NATUREMOVES => :JUDGMENT,
		:MIMICRY => :NORMAL,
		:MOVEDAMAGEBOOST => {
		1.3 => [:PSYSTRIKE, :AEROBLAST, 
				:ORIGINPULSE, :DOOMDUMMY, :MISTBALL, 
				:CRUSHGRIP, :LUSTERPURGE, :SECRETSWORD, 
				:PSYCHOBOOST, :RELICSONG, :SPACIALREND, 
				:HYPERSPACEHOLE, :ROAROFTIME, :LANDSWRATH, 
				:PRECIPICEBLADES, :DRAGONASCENT, :MOONGEISTBEAM, 
				:SUNSTEELSTRIKE, :PRISMATICLASER, :FLEURCANNON, 
				:DIAMONDSTORM, :GENESISSUPERNOVA, :SEARINGSUNRAZESMASH,
				:MENACINGMOONRAZEMAELSTROM],
		1.5 => [:MYSTICALFIRE, :MAGICALLEAF, :ANCIENTPOWER,:JUDGMENT,
			:SACREDFIRE, :EXTREMESPEED, :SACREDSWORD,:RETURN]},
		:MOVEMESSAGES => {
		"Legendary power accelerated the attack!" => [:PSYSTRIKE, 
			:AEROBLAST, :SACREDFIRE, :ORIGINPULSE, :DOOMDUMMY, 
			:JUDGMENT, :MISTBALL, :CRUSHGRIP, :LUSTERPURGE, 
			:SECRETSWORD, :PSYCHOBOOST, :RELICSONG, :SPACIALREND, 
			:HYPERSPACEHOLE, :ROAROFTIME, :LANDSWRATH, 
			:PRECIPICEBLADES, :DRAGONASCENT, :MOONGEISTBEAM, 
			:SUNSTEELSTRIKE, :PRISMATICLASER, :FLEURCANNON, 
			:DIAMONDSTORM, :GENESISSUPERNOVA, :SEARINGSUNRAZESMASH,
			:MENACINGMOONRAZEMAELSTROM],
		"The holy energy resonated with the attack!" => [:MYSTICALFIRE, 
			:MAGICALLEAF, :ANCIENTPOWER, :SACREDSWORD,:RETURN],
		"Godspeed!" => [:EXTREMESPEED]},
		:TYPEDAMAGEBOOST => {
		1.5 => [:FAIRY,:NORMAL],
		1.2 => [:PSYCHIC,:DRAGON],
		0.5 => [:GHOST,:DARK]},
		:TYPEMESSAGES => {
		"The holy energy resonated with the attack!" => [:FAIRY,:NORMAL],
		"The legendary energy resonated with the attack!" => [:PSYCHIC,:DRAGON],
		"The attack was cleansed..." => [:GHOST,:DARK]},
		:TYPECONDITION => {
			:FAIRY => "self.pbIsSpecial?(type)",
			:NORMAL => "self.pbIsSpecial?(type)",
			:DARK => "self.pbIsSpecial?(type)"
		},
		:FIELDCHANGE => {0 => [:LIGHTTHATBURNSTHESKY]},
		:CHANGEMESSAGE => {"The holy light was consumed!" => [:LIGHTTHATBURNSTHESKY]},
		:STATUSMOVEBOOST => [:WISH, :MIRACLEEYE, :COSMICPOWER, :NATURESMADNESS],
		:CHANGEEFFECTS => {},
		:SEED => :MAGICALSEED,
		:SEEDEFFECT => :MagicCoat,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} shrouded itself with Magic Coat!",
		:SEEDANIM => :MAGICCOAT,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 30 Mirror Arena
	PBFields::MIRRORA => {
    	:FIELDNAME => "Mirror Arena",  
    	:INTROMESSAGE => ["Mirror, mirror, on the field,","Who shall this fractured power wield?"],
		:FIELDGRAPHICS =>  "Mirror",
		:SECRETPOWERANIM => :MIRRORSHOT,
		:NATUREMOVES => :MIRRORSHOT,
		:MIMICRY => :STEEL,
		:MOVEDAMAGEBOOST => {
		1.5 => PBFields::BLINDINGMOVES,
		2.0 => [:MIRRORSHOT]},
		:MOVEMESSAGES => {
		"The reflected light was blinding!" => PBFields::BLINDINGMOVES,
		"The mirrors strengthened the attack!" => [:MIRRORSHOT]},
		:FIELDCHANGE => {
		0 => PBFields::QUAKEMOVES + [:BOOMBURST, :HYPERVOICE, :SELFDESTRUCT,
			 :EXPLOSION]},
		:STATUSMOVEBOOST => [:LIGHTSCREEN, :AURORAVEIL, :REFLECT, :MIRRORMOVE,
		:MIRRORCOAT, :DOUBLETEAM, :FLASH],
		:CHANGEEFFECTS => {},
		:SEED => :SYNTHETICSEED,
		:SEEDEFFECT => :MagicCoat,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} shrouded itself with Magic Coat!",
		:SEEDANIM => :MAGICCOAT,
		:SEEDSTATS => {PBStats::EVASION => 1}
		},
	# 31 Fairy Tale Field
	PBFields::FAIRYTALEF => {
		:FIELDNAME => "Fairy Tale Field",
		:INTROMESSAGE => "Once upon a time...",
		:FIELDGRAPHICS =>  "FairyTale",
		:SECRETPOWERANIM => :SLASH,
		:NATUREMOVES => :SECRETSWORD,
		:MIMICRY => :FAIRY,
		:MOVEDAMAGEBOOST => {
		1.5 => [:NIGHTSLASH, :LEAFBLADE, :PSYCHOCUT, 
						:SMARTSTRIKE, :AIRSLASH, :SOLARBLADE, :MAGICALLEAF, 
						:MYSTICALFIRE, :ANCIENTPOWER, :RELICSONG, 
						:SPARKLINGARIA, :MOONGEISTBEAM, :FLEURCANNON,
						:OCEANICOPERETTA, :MENACINGMOONRAZEMAELSTROM],
		2.0 => [:DRAININGKISS]},
		:MOVEMESSAGES => {
		"The blade cuts true!" => [:NIGHTSLASH, :LEAFBLADE, :PSYCHOCUT, 
			:SMARTSTRIKE, :AIRSLASH, :SOLARBLADE],
		"The magical energy strengthened the attack!" => [:MAGICALLEAF, 
		:MYSTICALFIRE, :ANCIENTPOWER, :RELICSONG, 
		:SPARKLINGARIA, :MOONGEISTBEAM, :FLEURCANNON, :OCEANICOPERETTA,
		:MENACINGMOONRAZEMAELSTROM],
		"True love never hurt so badly!" => [:DRAININGKISS]},
		:TYPETYPEMOD => {:DRAGON => [:FIRE]},
		:TYPEDAMAGEBOOST => {
		1.5 => [:STEEL,:FAIRY],
		2.0 => [:DRAGON]},
		:TYPEMESSAGES => {
		"For ever after!" => [:FAIRY],
		"For justice!" => [:STEEL],
		"The foul beast's attack gained strength!" => [:DRAGON]},
		:STATUSMOVEBOOST => [:KINGSSHIELD, :SPIKYSHIELD, :CRAFTYSHIELD, :FLOWERSHIELD,
			:ACIDARMOR, :NOBLEROAR, :SWORDSDANCE, :WISH, :HEALINGWISH,
			:MIRACLEEYE, :FORESTSCURSE, :FLORALHEALING],
		:CHANGEEFFECTS => {},
		:SEED => :MAGICALSEED,
		:SEEDEFFECT => :KingsShield,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "The Magical Seed shielded {1} against damage!",
		:SEEDANIM => :KINGSSHIELD,
		:SEEDSTATS => {}
		},
	# 32 Dragon's Den
	PBFields::DRAGONSD => {
		:FIELDNAME => "Dragon's Den",
		:INTROMESSAGE => "If you wish to slay a dragon...",
		:FIELDGRAPHICS =>  "DragonsDen",
		:SECRETPOWERANIM => :DRAGONPULSE,
		:NATUREMOVES => :DRAGONPULSE,
		:MIMICRY => :DRAGON,
		:MOVEDAMAGEBOOST => {
		1.5 => [:MEGAKICK, :MAGMASTORM, :LAVAPLUME],
		2.0 => [:SMACKDOWN, :THOUSANDARROWS, :DRAGONASCENT, 
						:PAYDAY, :TECTONICRAGE, :CONTINENTALCRUSH]},
		:MOVEMESSAGES => {
		"Trial of the Dragon!!!" => [:MEGAKICK], 
		"The lava strengthened the attack!" => [:MAGMASTORM, :LAVAPLUME],
		"{1} was knocked into the lava!" => [:SMACKDOWN, :THOUSANDARROWS],
		"The draconic energy boosted the attack!" => [:DRAGONASCENT], 
		"money money money money money mothafucka" => [:PAYDAY]},
		:MOVETYPEMOD => {:FIRE => [:SMACKDOWN, :THOUSANDARROWS, :TECTONICRAGE, :CONTINENTALCRUSH]},
		:TYPEDAMAGEBOOST => {
		1.5 => [:DRAGON, :FIRE],
		0.5 => [:ICE,:WATER]},
		:TYPEMESSAGES => {
		"The lava's heat boosted the flame!" => [:FIRE],
		"The draconic energy boosted the attack!" => [:DRAGON],
		"The lava's heat softened the attack..." => [:ICE,:WATER]},
		:FIELDCHANGE => {PBFields::CAVE => [:GLACIATE, :SUBZEROSLAMMER, :OCEANICOPERETTA, :HYDROVORTEX]},
		:CHANGEMESSAGE => {
			"The lava was frozen solid!" => [:GLACIATE, :SUBZEROSLAMMER],
			"The lava solidified!" => [:OCEANICOPERETTA, :HYDROVORTEX]},
		:STATUSMOVEBOOST => [:DRAGONDANCE, :NOBLEROAR],
		:CHANGEEFFECTS => {},
		:SEED => :ELEMENTALSEED,
		:SEEDEFFECT => :FlashFire,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} raised its Fire power!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 33 Flower Garden Field
	PBFields::FLOWERGARDENF => { #fuck
		:FIELDNAME => "Flower Garden Field",
		:INTROMESSAGE => "Seeds line the field.",
		:FIELDGRAPHICS => "FlowerGarden0", #fuck?
		:SECRETPOWERANIM => :SWEETSCENT, #fuck
		:NATUREMOVES => :GROWTH, #later stages handled in function
		:MIMICRY => :GRASS,
		:MOVEDAMAGEBOOST => {}, #fuck
		:MOVEMESSAGES => {}, #fuck
		:FIELDCHANGE => {PBFields::BURNINGF => PBFields::IGNITEMOVES},
		:CHANGEMESSAGE => {"The garden caught fire!" => PBFields::IGNITEMOVES},
		:CHANGECONDITION => {PBFields::BURNINGF => "ignitecheck && @battle.field.counter > 1"},
		:DONTCHANGEBACKUP => PBFields::IGNITEMOVES,
		:STATUSMOVEBOOST => [:GROWTH, :ROTOTILLER, :RAINDANCE, 
		:WATERSPORT, :SUNNYDAY, :FLOWERSHIELD, :SWEETSCENT, 
		:INGRAIN, :FLORALHEALING],
		:CHANGEEFFECTS => {},
		:SEED => :SYNTHETICSEED,
		:SEEDEFFECT => :Ingrain,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} planted its roots!",
		:SEEDANIM => :INGRAIN,
		:SEEDSTATS => {PBStats::SPDEF => 1}
		},
	# 34 Starlight Arena
	PBFields::STARLIGHTA => {
		:FIELDNAME => "Starlight Arena",
		:INTROMESSAGE => "Starlight fills the battlefield.",
		:FIELDGRAPHICS =>  "Starlight",
		:SECRETPOWERANIM => :SWIFT,
		:NATUREMOVES => :MOONBLAST,
		:MIMICRY => :DARK,
		:MOVEDAMAGEBOOST => {
		1.5 => [:AURORABEAM, :SIGNALBEAM, :FLASHCANNON, 
				:LUSTERPURGE, :DAZZLINGGLEAM, :MIRRORSHOT, 
				:TECHNOBLAST, :SOLARBEAM, :PHOTONGEYSER, 
				:MOONBLAST],
		2.0 => [:DRACOMETEOR, :METEORMASH, :COMETPUNCH, 
				:SPACIALREND, :SWIFT, :HYPERSPACEHOLE, 
				:HYPERSPACEFURY, :MOONGEISTBEAM, :SUNSTEELSTRIKE,
				:BLACKHOLEECLIPSE, :SEARINGSUNRAZESMASH, :MENACINGMOONRAZEMAELSTROM],
		4.0 => [:DOOMDUMMY]},
		:MOVEMESSAGES => {
		"Starlight surged through the attack!" => [:AURORABEAM, :SIGNALBEAM, 
			:FLASHCANNON, :LUSTERPURGE, :DAZZLINGGLEAM, :MIRRORSHOT, 
			:TECHNOBLAST, :SOLARBEAM, :PHOTONGEYSER],
		"Lunar energy surged through the attack!" => [:MOONBLAST],
		"The astral energy boosted the attack!" => [:DRACOMETEOR, :METEORMASH, 
			:COMETPUNCH, :SPACIALREND, :SWIFT,  
			:HYPERSPACEFURY, :MOONGEISTBEAM, :SUNSTEELSTRIKE, 
			:BLACKHOLEECLIPSE, :SEARINGSUNRAZESMASH, :MENACINGMOONRAZEMAELSTROM],
		"The astral vortex accelerated the attack!" => [:HYPERSPACEHOLE],
		"A star came crashing down!" => [:DOOMDUMMY]},
		:MOVETYPEMOD => {:FIRE => [:DOOMDUMMY]},
		:TYPETYPEMOD => {:FAIRY => [:DARK]},
		:TYPEDAMAGEBOOST => {
		1.5 => [:DARK,:PSYCHIC],
		1.3 => [:FAIRY]},
		:TYPEMESSAGES => {
		"Starlight supercharged the attack!" => [:FAIRY],
		"The night sky boosted the attack!" => [:DARK],
		"The astral energy boosted the attack!" => [:PSYCHIC]},
		:FIELDCHANGE => {0 => [:LIGHTTHATBURNSTHESKY]},
		:CHANGEMESSAGE => {"The cosmic light was consumed!" => [:LIGHTTHATBURNSTHESKY]},
		:STATUSMOVEBOOST => [:COSMICPOWER, :FLASH, :WISH, :HEALINGWISH, :LUNARDANCE, :MOONLIGHT],
		:CHANGEEFFECTS => {},
		:SEED => :MAGICALSEED,
		:SEEDEFFECT => :Wish,
		:SEEDEFFECTVAL => 2,
		:SEEDEFFECTSTR => "A wish was made for {1}!",
		:SEEDANIM => :WISH,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 35 New World
	PBFields::NEWW => {
		:FIELDNAME => "New World",
		:INTROMESSAGE => ["From darkness, from stardust,","From memories of eons past and visions yet to come..."],
		:FIELDGRAPHICS =>  "NewWorld",
		:SECRETPOWERANIM => :ROAROFTIME,
		:NATUREMOVES => :SPACIALREND,
		:MIMICRY => :QMARKS, #RNG
		:MOVEDAMAGEBOOST => {
		1.5 => [:AURORABEAM, :SIGNALBEAM, :FLASHCANNON, 
				:DAZZLINGGLEAM, :MIRRORSHOT, :PHOTONGEYSER, 
				:PSYSTRIKE, :AEROBLAST, :SACREDFIRE, :MISTBALL, 
				:LUSTERPURGE, :ORIGINPULSE, :PRECIPICEBLADES, 
				:DRAGONASCENT, :PSYCHOBOOST, :ROAROFTIME, 
				:MAGMASTORM, :CRUSHGRIP, :JUDGMENT, :SEEDFLARE, 
				:SHADOWFORCE, :SEARINGSHOT, :VCREATE, 
				:SECRETSWORD, :SACREDSWORD, :RELICSONG, 
				:FUSIONBOLT, :FUSIONFLARE, :ICEBURN, 
				:FREEZESHOCK, :BOLTSTRIKE, :BLUEFLARE, 
				:TECHNOBLAST, :OBLIVIONWING, :LANDSWRATH, 
				:THOUSANDARROWS, :THOUSANDWAVES, :DIAMONDSTORM, 
				:STEAMERUPTION, :COREENFORCER, :FLEURCANNON, 
				:PRISMATICLASER, :SUNSTEELSTRIKE, :SPECTRALTHIEF, 
				:MOONGEISTBEAM, :MULTIATTACK, :MINDBLOWN, 
				:PLASMAFISTS, :EARTHPOWER, :POWERGEM, 
				:ERUPTION, :CONTINENTALCRUSH, :GENESISSUPERNOVA,
				:SOULSTEALING7STARSTRIKE, :SEARINGSUNRAZESMASH,
				:MENACINGMOONRAZEMAELSTROM],
		2.0 => [:VACUUMWAVE, :DRACOMETEOR, :METEORMASH, 
				:MOONBLAST, :COMETPUNCH, :SWIFT, 
				:HYPERSPACEHOLE, :SPACIALREND, :HYPERSPACEFURY, 
				:ANCIENTPOWER, :FUTUREDUMMY, :BLACKHOLEECLIPSE],
		4.0 => [:DOOMDUMMY],
		0.25 => [:EARTHQUAKE, :MAGNITUDE, :BULLDOZE]},
		:MOVEACCURACYBOOST => {85 => [:DARKVOID]},
		:MOVEMESSAGES => {
		"The light shone through the infinite darkness!" => [:AURORABEAM, 
			:SIGNALBEAM, :FLASHCANNON, :DAZZLINGGLEAM, 
			:MIRRORSHOT, :PHOTONGEYSER],
		"The ethereal energy strengthened the attack!" => [:PSYSTRIKE, :AEROBLAST,
			:SACREDFIRE, :MISTBALL, :LUSTERPURGE, :ORIGINPULSE, 
			:PRECIPICEBLADES, :DRAGONASCENT, :PSYCHOBOOST, 
			:ROAROFTIME, :MAGMASTORM, :CRUSHGRIP, :JUDGMENT, 
			:SEEDFLARE, :SHADOWFORCE, :SEARINGSHOT, :VCREATE, 
			:SECRETSWORD, :SACREDSWORD, :RELICSONG, :FUSIONBOLT, 
			:FUSIONFLARE, :ICEBURN, :FREEZESHOCK, :BOLTSTRIKE, 
			:BLUEFLARE, :TECHNOBLAST, :OBLIVIONWING, :LANDSWRATH, 
			:THOUSANDARROWS, :THOUSANDWAVES, :DIAMONDSTORM, 
			:STEAMERUPTION, :COREENFORCER, :FLEURCANNON, 
			:PRISMATICLASER, :SUNSTEELSTRIKE, :SPECTRALTHIEF, 
			:MOONGEISTBEAM, :MULTIATTACK, :MINDBLOWN, 
			:PLASMAFISTS, :GENESISSUPERNOVA, :SOULSTEALING7STARSTRIKE,
			:SEARINGSUNRAZESMASH, :MENACINGMOONRAZEMAELSTROM], 
		"The germinal matter amassed in the attack!" => [:EARTHPOWER, :POWERGEM, 
			:ERUPTION, :CONTINENTALCRUSH],
		"The astral energy boosted the attack!" => [:VACUUMWAVE, :DRACOMETEOR, 
			:METEORMASH, :MOONBLAST, :COMETPUNCH, :SWIFT, 
			:HYPERSPACEHOLE, :SPACIALREND, :HYPERSPACEFURY, 
			:ANCIENTPOWER, :FUTUREDUMMY],
		"A star came crashing down on {1}!" => [:DOOMDUMMY], 
		"{1} was swallowed up by the void!" => [:BLACKHOLEECLIPSE],
		"The unformed land diffused the attack..." => [:EARTHQUAKE, 
			:MAGNITUDE, :BULLDOZE]},
		:MOVETYPEMOD => {:FIRE => [:DOOMDUMMY]},
		:TYPEDAMAGEBOOST => {1.5 => [:DARK]},
		:TYPEMESSAGES => {"Infinity boosted the attack!" => [:DARK]},
		:FIELDCHANGE => {PBFields::STARLIGHTA => [:GRAVITY, :GEOMANCY]},
		:DONTCHANGEBACKUP => [:GRAVITY],
		:CHANGEMESSAGE => {
		"The world's matter reformed!" => [:GRAVITY],
		"The world was regenerated!" => [:GEOMANCY]},
		:STATUSMOVEBOOST => [:DARKVOID, :HEARTSWAP, :TRICKROOM, :MAGICROOM, :WONDERROOM, :COSMICPOWER, :FLASH, :MOONLIGHT, :NATURESMADNESS],
		:CHANGEEFFECTS => {},
		:SEED => :MAGICALSEED,
		:SEEDEFFECT => :HyperBeam,
		:SEEDEFFECTVAL => 1,
		:SEEDEFFECTSTR => "{1} must recharge!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::ATTACK => 1,PBStats::DEFENSE => 1,PBStats::SPEED => 1,PBStats::SPATK => 1,PBStats::SPDEF => 1}
		},
	# 36 Inverse Field
	PBFields::INVERSEF => {
		:FIELDNAME => "Inverse Field",
		:INTROMESSAGE => "!trats elttaB",
		:FIELDGRAPHICS =>  "Inverse",
		:SECRETPOWERANIM => :CONFUSION,
		:NATUREMOVES => :TRICKROOM,
		:MIMICRY => :NORMAL,
		:MOVEDAMAGEBOOST => {},
		:MOVEMESSAGES => {},
		:FIELDCHANGE => {},
		:CHANGEMESSAGE => {},
		:STATUSMOVEBOOST => [],
		:CHANGEEFFECTS => {},
		:SEED => :MAGICALSEED,
		:SEEDEFFECT => :HyperBeam,
		:SEEDEFFECTVAL => 1,
		:SEEDEFFECTSTR => "{1} must recharge!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::ATTACK => 1,PBStats::DEFENSE => 1,PBStats::SPEED => 1,PBStats::SPATK => 1,PBStats::SPDEF => 1}
		},
	# 37 Psychic Terrain
	PBFields::PSYCHICT => {
		:FIELDNAME => "Psychic Terrain",
		:INTROMESSAGE => "The field became mysterious!",
		:FIELDGRAPHICS =>  "Psychic",
		:SECRETPOWERANIM => :PSYCHIC,
		:NATUREMOVES => :PSYCHIC,
		:MIMICRY => :PSYCHIC, #easy
		:MOVEDAMAGEBOOST => {
		1.5 => [:HEX, :MAGICALLEAF, :MYSTICALFIRE, 
						:MOONBLAST, :AURASPHERE, :MINDBLOWN]},
		:MOVEACCURACYBOOST => {90 => [:HYPNOSIS]},
		:MOVEMESSAGES => {
		"The psychic energy strengthened the attack!" => [:HEX, :MAGICALLEAF, 
			:MYSTICALFIRE, :MOONBLAST, :AURASPHERE, :MINDBLOWN]},
		:TYPEDAMAGEBOOST => {1.5 => [:PSYCHIC]},
		:TYPEMESSAGES => {"The Psychic Terrain strengthened the attack!" => [:PSYCHIC]},
		:TYPECONDITION => {:ELECTRIC => "!attacker.isAirborne?" },
		:FIELDCHANGE => {},
		:CHANGEMESSAGE => {},
		:STATUSMOVEBOOST => [:CALMMIND, :COSMICPOWER, :KINESIS, :MEDITATE,
			:NASTYPLOT, :HYPNOSIS, :TELEKINESIS, :GRAVITY, :MAGICROOM,
			:TRICKROOM, :WONDERROOM],
		:CHANGEEFFECTS => {},
		:SEED => :MAGICALSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1} became confused!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::SPATK => 2}
		},
	PBFields::CLOUDS => {
		:FIELDGRAPHICS =>  "Clouds",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEEFFECTS => {},
		:SEED => {}
	},	
	PBFields::DARKNESS => {
		:FIELDGRAPHICS =>  "Darkness",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEEFFECTS => {},
		:SEED => {}
	},
	PBFields::CELLIACENTRAL => {
		:FIELDGRAPHICS =>  "CelliaCentral",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEEFFECTS => {},
		:SEED => {}
	}, 
	PBFields::CELLIANORTH => {
		:FIELDGRAPHICS =>  "CelliaNorth",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEEFFECTS => {},
		:SEED => {}
	}, 
	PBFields::CELLIASOUTH => {
		:FIELDGRAPHICS =>  "CelliaSouth",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEEFFECTS => {},
		:SEED => {}
	}, 
	PBFields::CELLIAEAST => {
		:FIELDGRAPHICS =>  "CelliaEast",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEEFFECTS => {},
		:SEED => {}
	}, 
	PBFields::NIGHTCLUB => {
		:FIELDGRAPHICS =>  "Nightclub",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEEFFECTS => {},
		:SEED => {}
	}, 
	PBFields::SOOTGRASS => {
		:FIELDGRAPHICS =>  "SootGrass",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEEFFECTS => {},
		:SEED => {}
	}, 
	PBFields::SEWERS => {
		:FIELDGRAPHICS =>  "Sewers",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEEFFECTS => {},
		:SEED => {}
	}, 
	PBFields::INDOORA => {
		:FIELDGRAPHICS =>  "IndoorA",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEMESSAGE => {},
		:CHANGEEFFECTS => {},
		:SEED => {}
		},
	PBFields::INDOORB => {
		:FIELDGRAPHICS =>  "IndoorB",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEMESSAGE => {},
		:CHANGEEFFECTS => {},
		:SEED => {}
		},
	PBFields::INDOORC => {
		:FIELDGRAPHICS =>  "IndoorC",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEMESSAGE => {},
		:CHANGEEFFECTS => {},
		:SEED => {}
		},
	PBFields::CITY => {
		:FIELDGRAPHICS =>  "City",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEMESSAGE => {},
		:CHANGEEFFECTS => {},
		:SEED => {}
		},
	PBFields::CITYNEW => {
		:FIELDGRAPHICS =>  "CityNew",
		:SECRETPOWERANIM => :TRIATTACK,
		:NATUREMOVES => :TRIATTACK,
		:MIMICRY => :NORMAL,
		:CHANGEEFFECTS => {},
		:SEED => {}
		},

}